version: '3.3'
services:
  app-mysql-db:
    image: mysql:8.0
    container_name: "app-mysql-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --lower_case_table_names=1
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - "internalnet"


  app-web:
    container_name: app-web
    build: ./web
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - 5000:5000
    depends_on:
      - app-mysql-db
    networks:
      - "internalnet"


networks:
  internalnet:
    driver: bridge